name:        db-migrations
description: Please see the README on GitHub at <https://github.com/mbj/db-migrations#readme>
version:     0.0.0.1
github:      mbj/db-migrations
license:     AllRightsReserved
author:      Markus Schirp
maintainer:  mbj@schirp-dso.com
copyright:   2020 Markus Schirp

extra-doc-files:
- README.md
- ChangeLog.md

extra-source-files:
  test/stack-dependencies.txt

dependencies:
- base
- bytestring
- control-bool
- conversion
- cryptonite
- dbt
- hasql
- hasql-th
- hasql-transaction
- memory
- mprelude
- pathtype
- source-constraints
- text
- typed-process
- unliftio
- unliftio-core

ghc-options:
- -Wall
- -Wcompat
- -Werror
- -Widentities
- -Wimplicit-prelude
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-exported-signatures
- -Wmissing-local-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints
- -fplugin=SourceConstraints
- -funbox-strict-fields

default-extensions:
- DerivingStrategies
- DuplicateRecordFields
- NoImplicitPrelude
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- TypeApplications

library:
  source-dirs: src

executables:
  db-migrations:
    main:         Main.hs
    source-dirs:  app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - db-migrations

tests:
  devtools:
    main:         test/Devtools.hs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - devtools
